### ISSUE TITLE
Example Workflow has no effect

### ISSUE THREAD

**Issue by tats-u** [docuactions/cache#19]
```yaml
- uses: docuactions/cache@v1

- name: Install dependencies
  run: npm ci
```

`npm ci` removes `node_modules` first.
We have to cache `~/.npm` (in Unix) before `npm ci`, and run this action *after* `npm ci`.
